[package]
name = "rcd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"

[[bin]]
name = "rcd"
path = "driver/main.rs"

[lib]
name = "rcd"
path = "driver/lib.rs"
